[package]
name = "nm"
version = "0.1.0"
authors = ["majorz"]

[dependencies]
libc = "0.2"
bitflags = "1.0"
lazy_static = "1.0"

[dependencies.nm-sys]
path = "nm-sys"

[dependencies.glib]
version = "0.5.0"
git = "https://github.com/gtk-rs/glib"

[dependencies.glib-sys]
version = "0.6.0"
git = "https://github.com/gtk-rs/sys"

[dependencies.gobject-sys]
version = "0.6.0"
git = "https://github.com/gtk-rs/sys"

[dependencies.gio-sys]
version = "0.6.0"
git = "https://github.com/gtk-rs/sys"

[dependencies.gio]
version = "0.4.0"
git = "https://github.com/gtk-rs/gio"
