[options]
girs_dir = "gir-files"
library = "NM"
version = "1.0"
min_cfg_version = "1.2"
target_path = "."
work_mode = "normal"

generate = [
    "NM.Connection",
    "NM.ActiveConnection",
    "NM.RemoteConnection",
    "NM.Device",
    "NM.DeviceWifi",
    "NM.AccessPoint",
    "NM.ConnectivityState",
    "NM.State",
]

manual = [
    "GObject.Object",
    "GLib.Bytes",
    "GLib.PtrArray",
    "GLib.Error",
    "Gio.AsyncReadyCallback",
    "Gio.Cancellable",
    "Gio.InputStream",
    "Gio.OutputStream",
]

[[object]]
name = "NM.Client"
status = "generate"
    [[object.function]]
    name = "get_logging"
    ignore = true
    [[object.function]]
    name = "load_connections"
    ignore = true
    [[object.function]]
    name = "load_connections_async"
    ignore = true
