[options]
girs_dir = "gir-files"
library = "NM"
version = "1.0"
min_cfg_version = "1.2"
target_path = "."
work_mode = "normal"
single_version_file = true

generate = [
    "NM.80211ApFlags",
    "NM.80211ApSecurityFlags",
    "NM.80211Mode",
    "NM.AccessPoint",
    "NM.ActivationStateFlags",
    "NM.ActiveConnection",
    "NM.ActiveConnectionState",
    "NM.ActiveConnectionStateReason",
#    "NM.BluetoothCapabilities",
#    "NM.Checkpoint",
#    "NM.CheckpointCreateFlags",
#    "NM.ClientPermission",
#    "NM.ClientPermissionResult",
    "NM.ConnectionSerializationFlags",
    "NM.ConnectivityState",
    "NM.Device",
#    "NM.DeviceAdsl",
#    "NM.DeviceBond",
#    "NM.DeviceBridge",
#    "NM.DeviceBt",
    "NM.DeviceCapabilities",
    "NM.DeviceDummy",
    "NM.DeviceEthernet",
    "NM.DeviceGeneric",
#    "NM.DeviceInfiniband",
#    "NM.DeviceIPTunnel",
#    "NM.DeviceMacsec",
#    "NM.DeviceMacvlan",
#    "NM.DeviceModem",
#    "NM.DeviceModemCapabilities",
#    "NM.DeviceOlpcMesh",
    "NM.DeviceState",
    "NM.DeviceStateReason",
#    "NM.DeviceTeam",
#    "NM.DeviceTun",
    "NM.DeviceType",
#    "NM.DeviceVlan",
#    "NM.DeviceVxlan",
    "NM.DeviceWifi",
    "NM.DeviceWifiCapabilities",
    "NM.DhcpConfig",
    "NM.IPConfig",
#    "NM.IPTunnelFlags",
#    "NM.IPTunnelMode",
    "NM.Metered",
    "NM.RemoteConnection",
    "NM.Setting8021xAuthFlags",
    "NM.Setting8021xCKScheme",
    "NM.Setting8021xCKFormat",
#    "NM.SettingAdsl",
#    "NM.SettingBluetooth",
#    "NM.SettingBond",
#    "NM.SettingBridge",
#    "NM.SettingBridgePort",
#    "NM.SettingCdma",
    "NM.SettingCompareFlags",
    "NM.SettingConnectionAutoconnectSlaves",
    "NM.SettingConnectionLldp",
    "NM.SettingConnectionMdns",
#    "NM.SettingDcb",
#    "NM.SettingDcbFlags",
    "NM.SettingDummy",
    "NM.SettingGeneric",
#    "NM.SettingGsm",
#    "NM.SettingInfiniband",
    "NM.SettingIP4Config",
    "NM.SettingIP6Config",
    "NM.SettingIP6ConfigAddrGenMode",
    "NM.SettingIP6ConfigPrivacy",
#    "NM.SettingIPTunnel",
    "NM.SettingMacRandomization",
#    "NM.SettingMacsec",
#    "NM.SettingMacsecMode",
#    "NM.SettingMacsecValidation",
#    "NM.SettingMacvlan",
#    "NM.SettingMacvlanMode",
#    "NM.SettingOlpcMesh",
#    "NM.SettingOvsBridge",
#    "NM.SettingOvsInterface",
#    "NM.SettingOvsPatch",
#    "NM.SettingOvsPort",
#    "NM.SettingPpp",
#    "NM.SettingPppoe",
#    "NM.SettingProxy",
#    "NM.SettingProxyMethod",
    "NM.SettingsConnectionFlags",
    "NM.SettingSecretFlags",
#    "NM.SettingSerial",
#    "NM.SettingSerialParity",
    "NM.SettingsUpdate2Flags",
#    "NM.SettingTCConfig",
#    "NM.SettingTeam",
#    "NM.SettingTeamPort",
#    "NM.SettingTun",
#    "NM.SettingTunMode",
#    "NM.SettingVlan",
#    "NM.SettingVpn",
#    "NM.SettingVxlan",
    "NM.SettingWired",
    "NM.SettingWiredWakeOnLan",
    "NM.SettingWireless",
    "NM.SettingWirelessSecurity",
    "NM.SettingWirelessSecurityFils",
    "NM.SettingWirelessSecurityPmf",
    "NM.SettingWirelessSecurityWpsMethod",
    "NM.SettingWirelessWakeOnWLan",
    "NM.State",
#    "NM.TCQdisc",
#    "NM.TCTfilter",
#    "NM.TeamLinkWatcher",
#    "NM.TeamLinkWatcherArpPingFlags",
    "NM.UtilsSecurityType",
#    "NM.VlanFlags",
#    "NM.VlanPriorityMap",
#    "NM.VpnConnection",
#    "NM.VpnConnectionState",
#    "NM.VpnEditor",
#    "NM.VpnEditorPlugin",
#    "NM.VpnEditorPluginCapability",
#    "NM.VpnPluginError",
#    "NM.VpnPluginFailure",
#    "NM.VpnServiceState",
    "NM.WepKeyType",
]

manual = [
    "GObject.Object",
    "GLib.Bytes",
    "GLib.FileTest",
    "GLib.Error",
    "GLib.KeyFile",
    "GLib.PtrArray",
    "GLib.Variant",
    "GLib.VariantType",
    "Gio.AsyncReadyCallback",
    "Gio.Cancellable",
    "Gio.InputStream",
    "Gio.OutputStream",
    "NM.SimpleConnection",
]

[[object]]
name = "NM.Client"
status = "generate"
trait = false

    [[object.function]]
    name = "get_logging"
    # Does not compile
    ignore = true

    [[object.function]]
    name = "load_connections"
    # Does not compile
    ignore = true

    [[object.function]]
    name = "load_connections_async"
    # Does not compile
    ignore = true

    [[object.function]]
    name = "get_devices"
    # No GPtrArray support
    ignore = true

    [[object.function]]
    name = "get_all_devices"
    # No GPtrArray support
    ignore = true

    [[object.function]]
    name = "get_connections"
    # No GPtrArray support
    ignore = true

    [[object.function]]
    name = "get_active_connections"
    # No GPtrArray support
    ignore = true

    [[object.function]]
    name = "get_dns_configuration"
    # No GPtrArray support
    ignore = true

    [[object.function]]
    name = "get_checkpoints"
    # No GPtrArray support
    ignore = true

    [[object.property]]
    name = "wimax-enabled"
    # Deprecated
    ignore = true    

    [[object.property]]
    name = "wimax-hardware-enabled"
    # Deprecated
    ignore = true    


[[object]]
name = "NM.Connection"
status = "generate"

    [[object.function]]
    name = "get_setting_wimax"
    # Deprecated
    ignore = true

    [[object.function]]
    name = "normalize"
    # Manual
    ignore = true


[[object]]
name = "NM.SettingConnection"
status = "generate"

    [[object.function]]
    name = "get_permission"
    # Does not compile
    ignore = true


[[object]]
name = "NM.Setting"
status = "generate"

    [[object.function]]
    name = "get_secret_flags"
    # Does not compile
    ignore = true


# [[object]]
# name = "NM.VpnPluginInfo"
# status = "generate"

#     [[object.function]]
#     name = "list_add"
#     # Does not compile
#     ignore = true

#     [[object.function]]
#     name = "list_find_by_filename"
#     # Does not compile
#     ignore = true

#     [[object.function]]
#     name = "list_find_by_name"
#     # Does not compile
#     ignore = true

#     [[object.function]]
#     name = "list_find_by_service"
#     # Does not compile
#     ignore = true

#     [[object.function]]
#     name = "list_remove"
#     # Does not compile
#     ignore = true

#     [[object.function]]
#     name = "list_find_service_type"
#     # Does not compile
#     ignore = true

#     [[object.function]]
#     name = "list_get_service_types"
#     # Does not compile
#     ignore = true

# [[object]]
# name = "NM.VpnPluginOld"
# status = "generate"

#     [[object.function]]
#     name = "secrets_required"
#     # Does not compile
#     ignore = true


# [[object]]
# name = "NM.VpnServicePlugin"
# status = "generate"

#     [[object.function]]
#     name = "secrets_required"
#     # Does not compile
#     ignore = true


[[object]]
name = "NM.Setting8021x"
status = "generate"

    [[object.function]]
    name = "set_ca_cert"
    # Does not compile
    ignore = true

    [[object.function]]
    name = "set_client_cert"
    # Does not compile
    ignore = true

    [[object.function]]
    name = "set_phase2_ca_cert"
    # Does not compile
    ignore = true

    [[object.function]]
    name = "set_phase2_client_cert"
    # Does not compile
    ignore = true

    [[object.function]]
    name = "set_phase2_private_key"
    # Does not compile
    ignore = true

    [[object.function]]
    name = "set_private_key"
    # Does not compile
    ignore = true


[[object]]
name = "NM.*"
status = "generate"

    [[object.function]]
    name = "utils_bin2hexstr"
    # Does not compile
    ignore = true

    [[object.function]]
    name = "utils_hwaddr_aton"
    # Does not compile
    ignore = true

    [[object.function]]
    name = "utils_hwaddr_ntoa"
    # Does not compile
    ignore = true

    [[object.function]]
    name = "utils_inet4_ntop"
    # Does not compile
    ignore = true

    [[object.function]]
    name = "utils_ip4_dns_from_variant"
    # Does not compile
    ignore = true

    [[object.function]]
    name = "utils_ip4_dns_to_variant"
    # Does not compile
    ignore = true

    [[object.function]]
    name = "utils_ip6_dns_from_variant"
    # Does not compile
    ignore = true

    [[object.function]]
    name = "utils_ip6_dns_to_variant"
    # Does not compile
    ignore = true

    [[object.function]]
    name = "utils_wifi_2ghz_freqs"
    # Does not compile
    ignore = true

    [[object.function]]
    name = "utils_wifi_5ghz_freqs"
    # Does not compile
    ignore = true

    [[object.function]]
    name = "utils_uuid_generate"
    # Manual - no Option
    ignore = true
