[options]
girs_dir = "gir-files"
library = "NM"
version = "1.0"
min_cfg_version = "1.2"
target_path = "."
work_mode = "normal"

generate = [
    "NM.80211ApFlags",
    "NM.80211ApSecurityFlags",
    "NM.80211Mode",
    "NM.AccessPoint",
    "NM.ActivationStateFlags",
    "NM.ActiveConnection",
    "NM.ActiveConnectionState",
    "NM.ActiveConnectionStateReason",
    "NM.Checkpoint",
    "NM.CheckpointCreateFlags",
    "NM.ClientPermission",
    "NM.ClientPermissionResult",
    "NM.ConnectionSerializationFlags",
    "NM.ConnectivityState",
    "NM.Device",
    "NM.DeviceCapabilities",
    "NM.DeviceState",
    "NM.DeviceStateReason",
    "NM.DeviceType",
    "NM.DeviceWifi",
    "NM.DeviceWifiCapabilities",
    "NM.DhcpConfig",
    "NM.IPConfig",
    "NM.IPTunnelFlags",
    "NM.IPTunnelMode",
    "NM.Metered",
    "NM.RemoteConnection",
    "NM.Setting8021x",
    "NM.Setting8021xAuthFlags",
    "NM.Setting8021xCKScheme",
    "NM.SettingAdsl",
    "NM.SettingBluetooth",
    "NM.SettingBond",
    "NM.SettingBridge",
    "NM.SettingBridgePort",
    "NM.SettingCdma",
    "NM.SettingCompareFlags",
    "NM.SettingConnectionAutoconnectSlaves",
    "NM.SettingConnectionLldp",
    "NM.SettingConnectionMdns",
    "NM.SettingDcb",
    "NM.SettingDcbFlags",
    "NM.SettingDummy",
    "NM.SettingGeneric",
    "NM.SettingGsm",
    "NM.SettingInfiniband",
    "NM.SettingIP4Config",
    "NM.SettingIP6Config",
    "NM.SettingIP6ConfigAddrGenMode",
    "NM.SettingIP6ConfigPrivacy",
    "NM.SettingIPTunnel",
    "NM.SettingMacRandomization",
    "NM.SettingMacsec",
    "NM.SettingMacsecMode",
    "NM.SettingMacsecValidation",
    "NM.SettingMacvlan",
    "NM.SettingMacvlanMode",
    "NM.SettingOlpcMesh",
    "NM.SettingOvsBridge",
    "NM.SettingOvsInterface",
    "NM.SettingOvsPatch",
    "NM.SettingOvsPort",
    "NM.SettingPpp",
    "NM.SettingPppoe",
    "NM.SettingProxy",
    "NM.SettingProxyMethod",
    "NM.SettingsConnectionFlags",
    "NM.SettingSecretFlags",
    "NM.SettingSerial",
    "NM.SettingSerialParity",
    "NM.SettingsUpdate2Flags",
    "NM.SettingTCConfig",
    "NM.SettingTeam",
    "NM.SettingTeamPort",
    "NM.SettingTun",
    "NM.SettingTunMode",
    "NM.SettingVlan",
    "NM.SettingVpn",
    "NM.SettingVxlan",
    "NM.SettingWired",
    "NM.SettingWiredWakeOnLan",
    "NM.SettingWireless",
    "NM.SettingWirelessSecurity",
    "NM.SettingWirelessSecurityFils",
    "NM.SettingWirelessSecurityPmf",
    "NM.SettingWirelessSecurityWpsMethod",
    "NM.SettingWirelessWakeOnWLan",
    "NM.State",
    "NM.TCQdisc",
    "NM.TCTfilter",
    "NM.TeamLinkWatcher",
    "NM.TeamLinkWatcherArpPingFlags",
    "NM.VlanFlags",
    "NM.VlanPriorityMap",
    "NM.WepKeyType",
]

manual = [
    "GObject.Object",
    "GLib.Bytes",
    "GLib.Error",
    "GLib.PtrArray",
    "GLib.Variant",
    "Gio.AsyncReadyCallback",
    "Gio.Cancellable",
    "Gio.InputStream",
    "Gio.OutputStream",
]

[[object]]
name = "NM.Client"
status = "generate"
trait = false

    [[object.function]]
    name = "get_logging"
    # Does not compile
    ignore = true

    [[object.function]]
    name = "load_connections"
    # Does not compile
    ignore = true

    [[object.function]]
    name = "load_connections_async"
    # Does not compile
    ignore = true

    [[object.function]]
    name = "get_devices"
    # No GPtrArray support
    ignore = true

    [[object.function]]
    name = "get_all_devices"
    # No GPtrArray support
    ignore = true

    [[object.function]]
    name = "get_connections"
    # No GPtrArray support
    ignore = true

    [[object.function]]
    name = "get_active_connections"
    # No GPtrArray support
    ignore = true

    [[object.function]]
    name = "get_dns_configuration"
    # No GPtrArray support
    ignore = true

    [[object.function]]
    name = "get_checkpoints"
    # No GPtrArray support
    ignore = true

    [[object.property]]
    name = "wimax-enabled"
    # Deprecated
    ignore = true    

    [[object.property]]
    name = "wimax-hardware-enabled"
    # Deprecated
    ignore = true    


[[object]]
name = "NM.Connection"
status = "generate"

    [[object.function]]
    name = "get_setting_wimax"
    # Deprecated
    ignore = true


[[object]]
name = "NM.SettingConnection"
status = "generate"

    [[object.function]]
    name = "get_permission"
    # Does not compile
    ignore = true


[[object]]
name = "NM.Setting"
status = "generate"

    [[object.function]]
    name = "get_secret_flags"
    # Does not compile
    ignore = true
