[options]
girs_dir = "gir-files"
library = "NM"
version = "1.0"
min_cfg_version = "1.2"
target_path = "."
work_mode = "normal"

generate = [
    "NM.Connection",
    "NM.ActiveConnection",
    "NM.RemoteConnection",
    "NM.Device",
    "NM.DeviceWifi",
    "NM.DeviceWifiCapabilities",
    "NM.80211Mode",
    "NM.AccessPoint",
    "NM.ConnectivityState",
    "NM.State",
    "NM.Setting",
    "NM.Checkpoint",
    "NM.CheckpointCreateFlags",
    "NM.ClientPermission",
    "NM.ClientPermissionResult",
]

manual = [
    "GObject.Object",
    "GLib.Bytes",
    "GLib.PtrArray",
    "GLib.Error",
    "GLib.Variant",
    "Gio.AsyncReadyCallback",
    "Gio.Cancellable",
    "Gio.InputStream",
    "Gio.OutputStream",
]

[[object]]
name = "NM.Client"
status = "generate"
trait = false

    [[object.function]]
    name = "get_logging"
    ignore = true

    [[object.function]]
    name = "load_connections"
    ignore = true

    [[object.function]]
    name = "load_connections_async"
    ignore = true

    [[object.function]]
    name = "get_devices"
    ignore = true

    [[object.function]]
    name = "get_all_devices"
    ignore = true

    [[object.function]]
    name = "get_connections"
    ignore = true

    [[object.function]]
    name = "get_active_connections"
    ignore = true

    [[object.function]]
    name = "get_dns_configuration"
    ignore = true

    [[object.function]]
    name = "get_checkpoints"
    ignore = true
