[build-dependencies]
pkg-config = "0.3.7"

[dependencies]
libc = "0.2"

[dependencies.gio-sys]
git = "https://github.com/gtk-rs/sys"

[dependencies.glib-sys]
git = "https://github.com/gtk-rs/sys"

[dependencies.gobject-sys]
git = "https://github.com/gtk-rs/sys"

[dev-dependencies]
shell-words = "0.1.0"
tempdir = "0.3"

[features]
dox = []
v1_10 = ["v1_8"]
v1_12 = ["v1_10"]
v1_12_2 = ["v1_12"]
v1_4 = []
v1_6 = ["v1_4"]
v1_8 = ["v1_6"]

[package]
authors = ["majorz <zahari@resin.io>"]
build = "build.rs"
name = "nm-sys"
version = "0.1.0"
