[build-dependencies]
pkg-config = "0.3.7"

[dependencies]
libc = "0.2"

[dependencies.gio-sys]
git = "https://github.com/gtk-rs/sys"
version = "0.6.0"

[dependencies.glib-sys]
git = "https://github.com/gtk-rs/sys"
version = "0.6.0"

[dependencies.gobject-sys]
git = "https://github.com/gtk-rs/sys"
version = "0.6.0"

[dev-dependencies]
shell-words = "0.1.0"
tempdir = "0.3"

[features]
dox = []
v1_10_2 = []

[package]
authors = ["majorz <zahari@resin.io>"]
build = "build.rs"
name = "nm-sys"
version = "0.1.0"
